import '@styles/globals.css';
import StyledComponentsRegistry from '../lib/AntdRegistry';

export const metadata = {
    title: "House Renting",
    description: 'Generated by create next app'
}

const RootLayout = ({ children }) =>{
    return(
       <section>
           <html lang='en'>
           <body>
                <div className="app">
                <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
                </div>
            </body>
           </html>
       </section> 
    )
}
export default RootLayout;